log_level = "warn"
position = "Top"

[modules]
left = [["Workspaces"], "Tray"]
center = [
  "MediaPlayer",
  # "WindowTitle"
]
right = ["SystemInfo", "Clock", ["Privacy", "Settings"]]

[workspaces]
enable_workspace_filling = true
visibility_mode = "MonitorSpecific"

[window_title]
truncate_title_after_length = 75

[clock]
format = "%a %d %b %r"

[media_player]
max_title_length = 40

[system_info]
indicators = [
  # "IpAddress",
  "Cpu",
  "Memory",
  "Temperature",
  "UploadSpeed",
  "DownloadSpeed",
]


[system_info.temperature]
alert_threshold = 80
sensor = "acpitz temp1"

[settings]
# Power Commands
shutdown_cmd = "systemctl poweroff"
reboot_cmd = "systemctl reboot"
suspend_cmd = "systemctl suspend"
hibernate_cmd = "systemctl hibernate"

# Session Commands (for Hyprland)
lock_cmd = "hyprlock"
logout_cmd = "hyprctl dispatch exit"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman"

[appearance]
style = "Islands"
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = ["#7aa2f7", "#9ece6a"]
special_workspace_colors = ["#7aa2f7", "#9ece6a"]
font_name = "Iosevka Nerd Font"
scale_factor = 1.1

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
